# Generated by Django 4.1.1 on 2022-09-29 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('nit', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(default='Administrador', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('imagen', models.CharField(max_length=80)),
                ('contraseña', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCiclo3.empleado')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCiclo3.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=80)),
                ('monto', models.FloatField(max_length=10)),
                ('tipo_transaccion', models.CharField(default='Egreso', max_length=15)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCiclo3.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCiclo3.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCiclo3.empresa'),
        ),
    ]
