# Generated by Django 4.1.1 on 2022-09-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCiclo3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(default='Administrador', max_length=20),
        ),
    ]
