# Generated by Django 4.1.1 on 2022-09-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCiclo3', '0002_alter_rol_nombre_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
